# 🚀 AIRDOCS - Render Deployment Configuration
# Infrastructure as Code for Render.com

services:
  # Main AIRDOCS Backend Service
  - type: web
    name: airdocs-backend
    runtime: python3
    region: oregon
    plan: free
    buildCommand: cd ai-aggregator/backend && pip install -r requirements.txt
    startCommand: cd ai-aggregator/backend && uvicorn app:app --host 0.0.0.0 --port $PORT
    repo: https://github.com/satishskid/AIRdocs.git
    branch: main
    healthCheckPath: /health
    envVars:
      - key: ENVIRONMENT
        value: production
      - key: DEBUG
        value: "false"
      - key: API_HOST
        value: 0.0.0.0
      - key: ADMIN_API_KEY
        value: airdocs-render-admin-2024
      - key: TOKEN_ENCRYPTION_KEY
        value: airdocs-render-encryption-2024

  # Redis Cache Service
  - type: redis
    name: airdocs-redis
    region: oregon
    plan: free
    maxmemoryPolicy: allkeys-lru
